app-id: io.github.ilya_sotnikov.qUART
runtime: org.kde.Platform
runtime-version: '6.4'
sdk: org.kde.Sdk
command: qUART
finish-args:
  - --socket=wayland
  - --socket=x11
  - --device=dri
  - --device=all
  - --filesystem=home
modules:
  - name: qUART
    buildsystem: cmake-ninja
    build-options:
      build-args:
        - --share=network
      config-opts:
        - -DCMAKE_BUILD_TYPE=Release
    build-commands:
      - mkdir -p /app/share/applications
      - cp io.github.ilya_sotnikov.qUART.desktop /app/share/applications/
      - mkdir -p /app/share/icons/hicolor/48x48/apps
      - cp app.png /app/share/icons/hicolor/48x48/apps/io.github.ilya_sotnikov.qUART.png
    sources:
      - type: git
        url: https://github.com/ilya-sotnikov/qUART
        branch: main
      - type: file
        path: io.github.ilya_sotnikov.qUART.desktop
      - type: file
        path: ../../../icons/app.png
